### ISSUE TITLE
Fontbakery Report v1.000

### ISSUE THREAD

**Issue by Colophon-Foundry** [googlefonts/dm-mono#1]
Markdown Report too large to write inline and cannot upload `md` file

Uploading here as `txt` file.

[report.txt](https://github.com/Colophon-Foundry/dm-mono/files/4317129/report.txt)

**Comment by m4rc1e** [comment]
Thanks.

pretty much LGTM, only two issues.

Change copyright from:
`Copyright 2020 The DM Mono Authors (https://www.github.com/googlefonts/dm-mono)`
to
`Copyright 2020 The DM Mono Project Authors (https://www.github.com/googlefonts/dm-mono)`


Run all the fonts through `gftools fix-isfixedpitch` and include this command in build.sh.

**Comment by m4rc1e** [comment]
Regarding the monospace bits, https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb#monospace-fonts

**Comment by Colophon-Foundry** [comment]
Thanks @m4rc1e All updated as per b448313

**Comment by m4rc1e** [comment]
Perfect. Fonts can be shipped.
